### ISSUE TITLE
Should the posts render as raw HTML?

### ISSUE THREAD

**Issue by arrowtype** [TigersWay/eleventy-classic-blog-starter#1]
When I `npm install` this and run `eleventy --serve`, I get a site that looks like this:

![image](https://user-images.githubusercontent.com/45946693/102950545-db4e6d80-4498-11eb-9f03-3d80356e983a.png)

However, obviously I’m guessing it should look more like the [deployed demo](https://eleventy-classic-blog-starter.vercel.app/), with images, styled typography, etc etc.

Have I missed a step?

**Comment by TigersWay** [comment]
Hi,
From my memory, and the `package.json` file, I may say it should be:
- `npm run build` first,
- and then `npm run live`.

But you are right I did not write it down in the `README`

**Comment by arrowtype** [comment]
Sorry for the super-delayed confirmation, but yes, that works! Thanks for clarifying. :)

**Comment by TigersWay** [comment]
> Sorry for the super-delayed confirmation, but yes, that works! Thanks for clarifying. :)

Always welcome! 😃
